import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";

const noto_sans_jp = Noto_Sans_JP({subsets:['latin'], weight: ["400"]})

export const metadata: Metadata = {
  title: "TEXNITIS みやこ祭 Code Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans_jp.className}>
        {children}
      </body>
    </html>
  );
}
